server.port=0

spring.sql.init.mode=always

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/ewm-core-service
spring.datasource.username=ewm
spring.datasource.password=ewm

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Circuit breaker
resilience4j.circuitbreaker.instances.request-service.slidingWindowSize=5
resilience4j.circuitbreaker.instances.request-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.request-service.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.request-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.request-service.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.request-service.minimumNumberOfCalls=1
resilience4j.circuitbreaker.instances.request-service.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.retry.instances.eventServiceRetry.maxAttempts=3
resilience4j.retry.instances.eventServiceRetry.waitDuration=1s
resilience4j.retry.instances.eventServiceRetry.retryExceptions=ru.practicum.ewm.exception.microservice.EventMicroserviceUnavailableException

resilience4j.retry.instances.userServiceRetry.maxAttempts=3
resilience4j.retry.instances.userServiceRetry.waitDuration=1s
resilience4j.retry.instances.userServiceRetry.retryExceptions=ru.practicum.ewm.exception.microservice.UserMicroserviceUnavailableException

#---
spring.config.activate.on-profile=local

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:service-local-db
spring.datasource.username=h2-ewm-core-service-local
spring.datasource.password=password